name: bayes
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - attrs=19.3.0=py_0
  - backcall=0.1.0=py37_0
  - bleach=3.1.4=py_0
  - ca-certificates=2020.1.1=0
  - cairo=1.16.0=h18b612c_1001
  - certifi=2020.6.20=py37_0
  - cffi=1.14.0=py37he30daa8_1
  - chardet=3.0.4=py37_1003
  - cryptography=2.9.2=py37h1ba5d50_0
  - cudatoolkit=10.2.89=hfd86e86_1
  - cycler=0.10.0=py37_0
  - dbus=1.13.14=hb2f20db_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py37_0
  - expat=2.2.6=he6710b0_0
  - fontconfig=2.13.1=he4413a7_1000
  - freetype=2.9.1=h8a8886c_1
  - fribidi=1.0.9=h516909a_0
  - gettext=0.19.8.1=h9b4dc7a_1
  - glib=2.63.1=h3eb4bd4_1
  - gmp=6.1.2=h6c8ec71_1
  - graphite2=1.3.13=h23475e2_0
  - graphviz=2.42.3=h0511662_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb31296c_0
  - harfbuzz=2.4.0=h37c48d4_1
  - icu=58.2=he6710b0_3
  - idna=2.9=py_1
  - importlib-metadata=1.6.0=py37_0
  - importlib_metadata=1.6.0=0
  - intel-openmp=2020.1=217
  - ipykernel=5.1.4=py37h39e3cac_0
  - ipython=7.13.0=py37h5ca1d4c_0
  - ipython_genutils=0.2.0=py37_0
  - jedi=0.17.0=py37_0
  - jinja2=2.11.2=py_0
  - joblib=0.15.1=py_0
  - jpeg=9c=h14c3975_1001
  - json5=0.9.4=py_0
  - jsonschema=3.2.0=py37_0
  - jupyter_client=6.1.3=py_0
  - jupyter_core=4.6.3=py37_0
  - jupyterlab=2.1.3=py_0
  - jupyterlab_server=1.1.4=py_0
  - kiwisolver=1.2.0=py37hfd86e86_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libblas=3.8.0=14_openblas
  - libcblas=3.8.0=14_openblas
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.3=he6710b0_1
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - liblapack=3.8.0=14_openblas
  - libopenblas=0.3.7=h5ec1e0e_6
  - libpng=1.6.37=hbc83047_0
  - libsodium=1.0.16=h1bed415_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_0
  - libtool=2.4.6=h7b6447c_5
  - libuuid=2.32.1=h14c3975_1000
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=hea5a465_1
  - markupsafe=1.1.1=py37h7b6447c_0
  - matplotlib=3.1.3=py37_0
  - matplotlib-base=3.1.3=py37hef1b27d_0
  - mistune=0.8.4=py37h7b6447c_0
  - mkl=2020.1=217
  - nbconvert=5.6.1=py37_0
  - nbformat=5.0.6=py_0
  - ncurses=6.2=he6710b0_1
  - ninja=1.9.0=py37hfd86e86_0
  - notebook=6.0.3=py37_0
  - numpy=1.18.4=py37h8960a57_0
  - olefile=0.46=py37_0
  - openssl=1.1.1g=h7b6447c_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py37_1
  - pango=1.42.4=h7062337_4
  - parso=0.7.0=py_0
  - pcre=8.43=he6710b0_0
  - pexpect=4.8.0=py37_0
  - pickleshare=0.7.5=py37_0
  - pillow=7.1.2=py37hb39fc2d_0
  - pip=20.0.2=py37_3
  - pixman=0.38.0=h7b6447c_0
  - prometheus_client=0.7.1=py_0
  - prompt-toolkit=3.0.4=py_0
  - prompt_toolkit=3.0.4=0
  - ptyprocess=0.6.0=py37_0
  - pycparser=2.20=py_0
  - pygments=2.6.1=py_0
  - pyopenssl=19.1.0=py37_0
  - pyparsing=2.4.7=py_0
  - pyqt=5.9.2=py37h05f1152_2
  - pyrsistent=0.16.0=py37h7b6447c_0
  - pysocks=1.7.1=py37_0
  - python=3.7.7=hcff3b4d_5
  - python-dateutil=2.8.1=py_0
  - python-graphviz=0.14=py_0
  - python_abi=3.7=1_cp37m
  - pytorch=1.0.0=py3.7_cuda9.0.176_cudnn7.4.1_1
  - pyzmq=18.1.1=py37he6710b0_0
  - qt=5.9.7=h5867ecd_1
  - readline=8.0=h7b6447c_0
  - requests=2.23.0=py37_0
  - scikit-learn=0.23.1=py37h8a51577_0
  - scipy=1.4.1=py37ha3d9a3c_3
  - send2trash=1.5.0=py37_0
  - setuptools=46.4.0=py37_0
  - sip=4.19.8=py37hf484d3e_0
  - six=1.14.0=py37_0
  - sqlite=3.31.1=h62c20be_1
  - terminado=0.8.3=py37_0
  - testpath=0.4.4=py_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tk=8.6.8=hbc83047_0
  - torchvision=0.2.2=py_3
  - traitlets=4.3.3=py37_0
  - urllib3=1.25.8=py37_0
  - wcwidth=0.1.9=py_0
  - webencodings=0.5.1=py37_1
  - wheel=0.34.2=py37_0
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.9=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxpm=3.5.13=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-libxt=1.1.5=h516909a_1003
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.5=h7b6447c_0
  - zeromq=4.3.1=he6710b0_3
  - zipp=3.1.0=py_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pip:
    - altair==4.1.0
    - astor==0.8.1
    - base58==2.0.1
    - blinker==1.4
    - boto3==1.14.3
    - botocore==1.17.3
    - cachetools==4.1.0
    - docutils==0.15.2
    - enum-compat==0.0.3
    - gif==1.0.4
    - ipywidgets==7.5.1
    - jmespath==0.10.0
    - packaging==20.4
    - pandas==1.0.4
    - pathtools==0.1.2
    - protobuf==3.12.2
    - pydeck==0.4.0b2
    - pytz==2020.1
    - s3transfer==0.3.3
    - toml==0.10.1
    - toolz==0.10.0
    - tornado==5.1.1
    - tzlocal==2.1
    - validators==0.15.0
    - watchdog==0.10.2
    - widgetsnbextension==3.5.1

